### ISSUE TITLE
howtoinstall

### ISSUE THREAD

**Issue by flybirdkh** [IGBIllinois/cluster_accounting#17]
Hi

How to install it ,and Readme cannot direct me to install it correctly. 

Best wishes to you and look forwarding to your reply

**Comment by dslater82** [comment]
Hi,

Thanks for trying to get this installed.  I do see that I am missing some steps in the README.  I'll work on completing that.  We made this program and only have it installed here I believe.  Any help you can give to let me know the troubles you run into will help make this program better.

**Comment by dslater82** [comment]
The README has been improved awhile ago.
